apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-app-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mehedi-iut/simple-go-app.git
    targetRevision: test
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    # namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true