name: Test CI
on:
    push:
        branches:
            - master
    # workflow_dispatch:

jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        steps:
            - name: print
              run: |
                lsb_release -a